server:
  port: 8282

logging:
  level:
    io:
      netty: debug
      reactor: debug

spring:
  datasource:
    url: jdbc:hsqldb:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true